# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/benny/work/fpga/vivado/i2s2_2/Pmod-I2S2-Arty-S7-50.srcs/sources_1/bd/reciever/ip/reciever_axis_dwidth_converter_0_0/reciever_axis_dwidth_converter_0_0.xci
# IP: The module: 'reciever_axis_dwidth_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/benny/work/fpga/vivado/i2s2_2/Pmod-I2S2-Arty-S7-50.gen/sources_1/bd/reciever/ip/reciever_axis_dwidth_converter_0_0/reciever_axis_dwidth_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reciever_axis_dwidth_converter_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/benny/work/fpga/vivado/i2s2_2/Pmod-I2S2-Arty-S7-50.srcs/sources_1/bd/reciever/ip/reciever_axis_dwidth_converter_0_0/reciever_axis_dwidth_converter_0_0.xci
# IP: The module: 'reciever_axis_dwidth_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/benny/work/fpga/vivado/i2s2_2/Pmod-I2S2-Arty-S7-50.gen/sources_1/bd/reciever/ip/reciever_axis_dwidth_converter_0_0/reciever_axis_dwidth_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reciever_axis_dwidth_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
